primer/brand

.changeset/config.json, .github/workflows/ci.yml, .github/workflows/deploy_docs.yml, .github/workflows/deploy_docs_preview.yml, .github/workflows/integration_test_astro.yml, .github/workflows/integration_test_cra.yml, .github/workflows/integration_test_nextjs.yml, .github/workflows/integration_test_remix.yml, .github/workflows/release_canary.yml, .github/workflows/release_candidate.yml, .github/workflows/ui_test_accessibility.yml, .github/workflows/ui_test_primitives_diff.yml, .github/workflows/visual_test_storybook.yml, CONTRIBUTING.md, README.md, RELEASING.md, docs/content/getting-started/index.mdx, docs/content/index.mdx, docs/gatsby-config.js, docs/src/@primer/gatsby-theme-doctocat/components/hero.js, package-lock.json, package.json, scripts/build-storybook, src/FAQ/FAQ.tsx
fixes broken urls and content after changing repo name
=> Rename repo clean-up tasks

.github/workflows/integration_test_astro.yml, integration-tests/fixtures/KitchenSink.tsx, integration-tests/fixtures/index.cjs.ts, integration-tests/fixtures/index.esm.ts
Updates the kitchen sink fixture in our end-to-end consumer tests to include the recent form components.
https://user-images.githubusercontent.com/13340707/190112668-e7dafa86-0b19-4b32-93f8-8d02694b1422.mov
- Code review :) 
- Check the consumer / integration tests in CI pass
=> Update Next.js, CRA, Remix and Astro consumer tests with new form components

.github/workflows/deploy_docs.yml, .github/workflows/deploy_docs_preview.yml
🚧 Testing new reusable workflow... https://github.com/primer/.github/pull/6
=> Apply / Test new reusable deployment workflow 

packages/react/src/ButtonGroup/ButtonGroup.test.tsx
Adding unit tests for the ButtonGroup component.
- **added** unit tests for the ButtonGroup component
- Making sure the unit tests cover everything the component does technically
1. Open the code and run ```npm run test src/ButtonGroup/ButtonGroup.test.tsx```
=> Added tests for ButtonGroup

.changeset/itchy-cycles-relax.md, apps/docs/content/components/Stack.mdx, packages/react/src/Stack/Stack.stories.tsx, packages/react/src/Stack/Stack.tsx
Some minor updates to the Stack component to make it easier to use and easier to see the documentation.
- **added** custom class option to Stack component
- **updated** placeholder color to be more visible on different screens
- Seeing if the class works for adding custom CSS
- Seeing if the new color appears more readily on their browser
1. Open the Stack component in CI-deployed preview environment
2. Go to Stack story in Storybook
3. Verify that Stack behaves as described in the following issue.
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Stack Component Updates

apps/docs/content/components/Heading.mdx
While using the [`Heading` docs](https://primer.style/brand/components/Heading), I noticed the component description was incorrect.
- updated descriptive copy for the `Heading` component for accuracy
- is new copy accurate?
=> Update incorrect description of Heading

.changeset/wet-clocks-bake.md, packages/react/src/css/stylesheets.ts, packages/react/src/css/utilities.css, packages/react/src/css/utilities.css.d.ts
Adds a visually hidden utility class to our `main.css` bundle, which can be passed easily as a className to any react component.
Avoided created `VisuallyHidden` component on this occasion due to complexity in mitigating polymorphism and other unknown requirements right now. This is the quickest way to address our short-term needs.
- **added** a new utilities stylesheet with some blurb around what goes in there
-**ported** visually hidden CSS class verbatim
- Checking approach is reasonable
=> Add visually hidden utility class

apps/docs/content/components/AnchorNav.mdx, apps/docs/content/components/CTABanner.mdx, apps/docs/content/components/Checkbox.mdx, apps/docs/content/components/ComparisonTable.mdx, apps/docs/content/components/FAQ.mdx, apps/docs/content/components/FormControl.mdx, apps/docs/content/components/Heading.mdx, apps/docs/content/components/Hero.mdx, apps/docs/content/components/MinimalFooter.mdx, apps/docs/content/components/OrderedList.mdx, apps/docs/content/components/Radio.mdx, apps/docs/content/components/River.mdx, apps/docs/content/components/SectionIntro.mdx, apps/docs/content/components/Select.mdx, apps/docs/content/components/Stack.mdx, apps/docs/content/components/SubdomainNavBar.mdx, apps/docs/content/components/Testimonial.mdx, apps/docs/content/components/Text.mdx, apps/docs/content/components/TextInput.mdx
Fix broken links to component sources.
- **updated** broken source links in component docs/.
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Fix broken source links

apps/docs/package-lock.json, apps/docs/package.json, package-lock.json
- **updated** the Doctocat version to v4.4.0 to remove the `What's new` section form the main navigation
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Update doctocat to v4.4.0

.changeset/modern-rockets-live.md, packages/react/src/CTABanner/CTABanner.test.tsx, packages/react/src/CTABanner/CTABanner.tsx
Fixed a bug where the className was not forwarded to the base component
- Making sure tests pass and the class was passed
=> CTABanner Class Forwarding Bug Fix

apps/docs/content/components/Button.mdx
Adds "Accessibility reviewed" status to `Button` component 🎉 .
- Adds `a11yReviewed` to component status.
=> Add "accessibility reviewed" to `<Button>`

.changeset/red-pillows-enjoy.md, packages/design-tokens/src/tokens/functional/components/button/colors.js
In dark themes, the secondary button uses a border-default token for its border/shadow color, a solid dark color that makes the border to be almost invisible when used on top of other backgrounds (for instance, https://lgtm.github.com/). This PR adjust the secondary border to be transparent so it works on as many kinds of backgrounds as possible. We often use it in Hero, SubNav components with all kinds of backgrounds. The new value is based on dotcom secondary button, which is `rgba(255, 255, 255, 0.25)`.
To be aligned with the actual brand color management, these changes uses hsl values `hsl(var(--base-color-scale-white-0-hsl) / 25%)` as a temporary update, waiting for the new version of primitives that uses HEX values with transparency.
- **updated** secondary shadow color.
- Storybook …
=> [Button] Adjust secondary border color

package-lock.json, package.json
Discovered this while exploring Primer Brand with our intern– if you've never worked in this repo and you want to start Storybook, you'll need to build the lib first. I think it makes sense to just add it to the Storybook script (as in it shouldn't hurt?)
- Create a codespace on this PR and run `npm run start:storybook`
=> Update Storybook start script

package-lock.json, packages/react/package.json
🔴 Required to unblock next release. 
There was a regression introduced in the `@types/react` package between `17.0.50` and `17.0.59`, which caused certain props to be flagged as required when they shouldn't be. This bug has prevented release of the next version of the library, as compiler errors were detected during smoke tests on multiple website.
This dependency bug was fixed in the @types/react library here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65639
- **updated** @types/react to latest version to `17.0.64`, which is verified to fix the issue.
- Just checking that builds pass
1. Take the canary package
1. Open Resources Hub (or any site that uses PB)
1. Upgrade to canary version and test components like Heading or Checkbox 
- …
=> Upgrade @types/react to fix html attributes bug

apps/docs/content/components/Grid/index.mdx, apps/docs/content/components/Grid/react.mdx, apps/docs/content/components/Stack/index.mdx, apps/docs/content/components/Stack/react.mdx, apps/docs/src/@primer/gatsby-theme-doctocat/components/wrap-page-element.js
Add `Grid` and `Stack` design guidelines.
- **added** new ComponentLayout to `Grid` and `Stack` docs
- **added** design guidelines for `Grid` and `Stack`
- **added** footnotes styles
- 👀 Grid documentation: https://primer-63f891a15f-26139705.drafts.github.io/components/Grid 
- 👀 Stack documentation: https://primer-63f891a15f-26139705.drafts.github.io/components/Stack
- Epic: https://github.com/github/primer/issues/2433
- Tracking issue: https://github.com/github/primer/issues/2127
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> [Grid & Stack] Design guidelines

apps/docs/content/components/River/index.mdx, apps/docs/content/components/River/react.mdx
Add `River` design guidelines.
- **added** new ComponentLayout to `River`  docs
- **added** design guidelines for `River`
- 👀  documentation: https://primer-5b0e748761-26139705.drafts.github.io/components/River
- Epic: https://github.com/github/primer/issues/2433
- Tracking issue: https://github.com/github/primer/issues/1988
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> [River] Design guidelines

apps/docs/content/components/CTAForm/index.mdx, apps/docs/content/components/CTAForm/react.mdx
Added `CTA Form` Design Guidelines
- added new ComponentLayout to CTA Form docs
- added design guidelines
- 👀🙌  documentation: https://primer-b10e33d28d-26139705.drafts.github.io/components/CTAForm
- Epic: https://github.com/github/primer/issues/2231
- Design issue: https://github.com/github/galaxy.github.com/issues/21
- Component Issue: https://github.com/github/primer/issues/1751
- https://github.com/github/primer/issues/1983
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> [CTAForm] Design Guidelines

apps/docs/content/components/LogoSuite/index.mdx, apps/docs/content/components/LogoSuite/react.mdx, apps/docs/src/@primer/gatsby-theme-doctocat/nav.yml
Fixing some typos and errors in recently deployed docs.
🔗 [Docs](https://primer-ede126842d-26139705.drafts.github.io/components/LogoSuite)
1. Review the diff
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Fixing docs typos on logo suite

apps/docs/content/components/Pillar/index.mdx
Updates images in the design guidelines
Closes: https://github.com/github/primer/issues/2505
- **updated** Pillar docs images with the new UI
Design guidelines changes
Documentation: 
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> [Pillar] Update documentation

.github/pull_request_template.md
Add recommendations for site designers and FR duties to review Primer Brand PR. This was brought up during the last Primer Brand office [hours](https://docs.google.com/document/d/14-LG0ibLTtH5BkTl7hVvAfOp2Uilnp0ukKr_tU7sMcE/edit)
=> Update pull_request_template.md with Site Design guidance

apps/docs/content/components/Hero/index.mdx
- Replaced images to match the new Hero component.
- Made a new image for anatomy. 
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Update guidelines Hero

.changeset/swift-geckos-destroy.md, .github/workflows/integration_test_astro.yml, .github/workflows/integration_test_cra.yml, packages/react/src/Bento/Bento.module.css, packages/react/src/FAQ/FAQGroup.module.css, packages/react/src/Hero/Hero.module.css, packages/react/src/VideoPlayer/VideoPlayer.module.css
Part of https://github.com/github/primer/issues/2728
Fixes CRA tests
=> Fix CRA integration test workflow

apps/docs/content/components/River/index.mdx
- Updated the River Breakout images 
🔗 https://primer-c0c38c6d13-26139705.drafts.github.io/components/River
=> Breakout river – Image updates

.github/workflows/integration_test_nextjs.yml
Fixes NextJS integration tests by bumping the Node version in the test.
N/A
N/A
N/A
N/A
=> Fix Next14 Integration Tests

packages/react/src/EyebrowBanner/EyebrowBanner.features.stories.tsx
- Fixes eyebrow banner stories
1. Verify checks are passing
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Fix failing CI checks

packages/react/src/SubNav/SubNav.module.css
Fixes the following issues which are exclusive to dotcom, and discovered during release testing.
- Forced suppression of dotcoms global link underlines on hover
- Added minimal z-index to wide links container to counteract custom values applies to our landing pages 
- 
-
1.
1.
1.
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Patch: dotcom fixes for SubNav component

.github/workflows/integration_test_remix.yml
Fixing remix integration tests.
-
-
- 
-
1.
1.
1.
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Fixing remix integration tests

apps/docs/content/components/Button/index.mdx
Add small button usage guidance
=> Add small button usage guidance

packages/react/src/recipes/seo/Category/Category.visual.spec.ts, packages/react/src/recipes/seo/Category/CategoryPage.stories.tsx
=> fix linter issues

.changeset/hip-pumas-greet.md, apps/docs/content/components/LogoSuite/react.mdx, packages/react/src/LogoSuite/LogoSuite.module.css, packages/react/src/LogoSuite/LogoSuite.module.css.d.ts, packages/react/src/LogoSuite/LogoSuite.stories.tsx, packages/react/src/LogoSuite/LogoSuite.test.tsx, packages/react/src/LogoSuite/LogoSuite.tsx
This one adds the `stop` "speed" to `LogoSuite` component. 
A11y requested that we have a way to stop the scrollable content, because it's an 2.2.2 offense. So I figured this the easiest way to improve this component is to be able to toggle the `stop` speed. Kinda lousy name though. 
Simon tells me that the've told him that `prefers-reduced-motion` setting is sufficient to remedy 2.2.2, but I've got so many issues telling me that I need to add play/pause button.
So I'll need to talk with them once I get back from OOO.
But having this won't hurt though. 😆 
- **added** `stop` speed that stops the auto scrolling for a11y reasons so it can be programmatically toggled.
1. You'll have to do it manually... :(
- https://github.com/github/accessibility-audits/issues/7881
- …
=> Add the `idle` speed to LogoSuite so it can be programmatically stopped

packages/react/src/recipes/seo/Article/Article.tsx
[Link to discussion on Slack](https://github.slack.com/archives/C06UE379Y3U/p1718802455538099)
=> Add schema

apps/docs/README.md
Updating the docs README to reflect issues I encountered while setting up local dev
=> Update docs install instructions

apps/docs/content/components/VideoPlayer.mdx
Update links used by `VideoPlayer` component in docs to fix issue where video assets were not working in production.
1. Lets deploy and see whether it works!
- https://github.com/github/primer/issues/2448
=> update source link

.github/release_template.md, .github/workflows/release_canary.yml, .github/workflows/release_candidate.yml, .github/workflows/release_candidate_checklist.yml
Adds release conductor notes, checklist and automated reminder about the checklist to Release Tracking PRs.
Adapted from a [similar checklist added to PRC](https://github.com/primer/react/pull/2015).
- Please review docs and ask any questions if you have any
1. Scroll down to see the rendered version of the automated reminder
=> Add release conductor notes and workflow

apps/docs/content/components/IDE.mdx
Trivial: description tweak and backticks around `IDE` in prose
- `to enhancing` changed to `to enhance`
- added backticks around mentions of `IDE` in prose
- 
- 
-
1.
1.
1.
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Update IDE.mdx - description tweak and backticks around `IDE` in prose

package-lock.json, packages/react/src/recipes/SolutionTemplates/CategoryPage/CategoryPage.tsx, packages/react/src/recipes/SolutionTemplates/SolutionPage/SolutionPage.tsx, packages/react/src/recipes/SolutionTemplates/SolutionPage/UseCase/UseCase.stories.tsx
part of https://github.com/github/brand-marketing-design/issues/1469 (phase 2)
Adds recently shipped breakout banner to the solution templates
- Adds breakout banner to category and details pages (use-case only)
- Updates dark mode background color on category page to subtle
- Improved spacing on narrow viewports 
- Review implementation in storybook for design accuracy 
1. Open [this category page story](https://primer-d2c1809664-26139705.drafts.github.io/brand/storybook/?path=/story/recipes-solutions-categorypage--light) and cross-check against the [design](https://www.figma.com/design/AEuqwByyCCch6tf7YVgk3I/Solution-Page-Templates?node-id=604-53552&m=dev)
1. Open [this details page story](https://primer-d2c1809664-26139705.drafts.github.io/brand/storybook/?path=/story/recipes-solutions- …
=> Add breakout banner to solution templates

apps/docs/content/components/CTABanner/index.mdx, apps/docs/content/components/CTABanner/react.mdx
Resolves https://github.com/primer/brand/issues/675
- Mostly updating content on the react page
- Includes minor rewriting of content for consistency and brevity 
- Minor updates to overview page
- Keeping eye out for any other issues I've missed in the original issue
- Making sure I haven't introduced any new issues 😆 
1. [Overview page](https://primer-d575bfa61e-26139705.drafts.github.io/brand/components/CTABanner)
1. [React page](https://primer-d575bfa61e-26139705.drafts.github.io/brand/components/CTABanner/react)
=> Update and fix issues in CTA banner docs

packages/react/src/LogoSuite/LogoSuite.figma.tsx
This issue created a bug in Figma where the code would not be shown.
=> Fix for logoSuite code connect

package-lock.json, packages/design-tokens/package.json, packages/design-tokens/scripts/build-tokens.js, packages/design-tokens/scripts/style-dictionary.js, packages/design-tokens/src/tokens/functional/size/viewport.json
This fixes https://github.com/github/primer/issues/3891
-
-
- 
-
1.
1.
1.
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Using upstream config from primer/primitives

.changeset/shiny-balloons-dress.md, packages/design-tokens/scripts/build-tokens.js, packages/design-tokens/scripts/style-dictionary.js
-
-
- 
-
1.
1.
1.
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Replace touch formats with upstream

package-lock.json, packages/design-tokens/package.json, packages/design-tokens/scripts/style-dictionary.js
- **removed** prettier and prettier/sync from deps
- 
-
1.
1.
1.
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Replace javascript/module-v2 format with upstream

package-lock.json, packages/design-tokens/package.json, packages/design-tokens/scripts/build-tokens.js, packages/design-tokens/scripts/style-dictionary.js, packages/design-tokens/src/formats/color-mode-attributes.js, packages/design-tokens/src/formats/responsive-media-query.js, packages/design-tokens/src/formats/typescript-module-declarations-v2.js
-
-
- 
-
1.
1.
1.
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Cleanup by removing some unneeded transforms and moving a format into a file

.changeset/fair-garlics-remain.md
Adds missing changeset for #749
=> Add changeset for #749

packages/design-tokens/scripts/build-tokens.js, packages/design-tokens/src/tokens/functional/components/accordion/colors.js, packages/design-tokens/src/tokens/functional/components/action-menu/colors.js, packages/design-tokens/src/tokens/functional/components/anchor-nav/colors.js, packages/design-tokens/src/tokens/functional/components/breadcrumbs/colors.js, packages/design-tokens/src/tokens/functional/components/button/colors.js, packages/design-tokens/src/tokens/functional/components/comparison-table/colors.js, packages/design-tokens/src/tokens/functional/components/control/colors.js, packages/design-tokens/src/tokens/functional/components/cta-banner/colors.js, packages/design-tokens/src/tokens/functional/components/eyebrow-banner/colors.js, packages/design-tokens/src/tokens/functional/components/ide/colors.js, packages/design-tokens/src/tokens/functional/components/pagination/colors.js, packages/design-tokens/src/tokens/functional/components/prose/colors.js, packages/design-tokens/src/tokens/functional/components/river-story-scroll/colors.js, packages/design-tokens/src/tokens/functional/components/sub-nav/colors.js, packages/design-tokens/src/tokens/functional/components/subdomain-nav-bar/colors.js, packages/design-tokens/src/tokens/functional/components/video-player/colors.js
Remove namespace from js token files. In the future they should be updated to be json files.
=> Remove namespace from js token files

packages/react/src/Icon/Icon.module.css, packages/react/src/Icon/Icon.module.css.d.ts, packages/react/src/Icon/Icon.tsx
- Removes `<span>` from `Icon` component
- Sets a fixed padding to give an icon size of 20px.
- Modify props to extend SVGElement
=> Remove span

.changeset/lovely-jobs-lay.md, apps/docs/content/components/Icon.mdx, apps/docs/src/@primer/gatsby-theme-doctocat/nav.yml, packages/react/src/Bento/Bento.stories.tsx, packages/react/src/index.ts
Export Icon component and add documentation.
- Happy to export the component?
- Happy with the docs in their current state?
- https://github.com/primer/brand/issues/827#issuecomment-2497358178
=> export Icon component and add documentation

packages/react/src/Card/Card.module.css
Fixes a bug with the torchlight card border radius. See screenshots below and note the discrepancy between the border radius of the border, and the border radius of the background.
1. Check that the issue is resolved in Storybook
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> hotfix: fix torchlight card border radius

.changeset/warm-ads-return.md, apps/docs/content/components/IDE.mdx, package-lock.json, packages/react/src/IDE/IDE.features.stories.tsx, packages/react/src/IDE/IDE.module.css, packages/react/src/IDE/IDE.module.css.d.ts, packages/react/src/IDE/IDE.stories.tsx, packages/react/src/IDE/IDE.test.tsx, packages/react/src/IDE/IDE.tsx, packages/react/src/IDE/fixtures/content.ts, packages/react/src/hooks/useTabs.ts, packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.tsx
Enables keyboard navigation of the tabs within the IDE component. To enable this, it was necessary to remove the top-level `alternativeText` from the IDE component in favour of `alternativeText` per file, and for the chat.
- Removed `alternativeText` prop from `IDE`
- Added `alternativeText` prop to `IDE.Chat`
- Added `alternativeText` property to `IDEEditorFile` type
- Added `useTabs` hook to manage tab behaviour according to [the Tabs Pattern ARIA APG](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/). Everything listed in that document has been implemented, except:
- <kbd>Shift</kbd> + <kbd>F10</kbd>: Open associated popup menu (not relevant)
- <kbd>Delete</kbd>: Tab deletion (not relevant)
- Refactored `IDE.Editor` line animation to simplify logic
- Updated `IDE` documentation with …
=> IDE — Enable keyboard navigation, move alternativeText to individual files and chat

.github/release_template.md
This patch adds new pages to the release template. These pages have been worked on by the MPS team and are now ready to be included in the release checklist.
I will be communicating steps about enabling feature flags for the new pages in a private channel.
N/A
N/A
N/A
N/A
=> Update release template with new pages

apps/next-docs/package.json, package-lock.json
Fixes a missing styled-components build dependency for our next.js docs.
Preventing compilation and deployment of a preview link in the release tracking branch.
-
-
-
-
1.
1.
1.
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Fix missing styled-components build dependency

.github/workflows/deploy_docs.yml, .github/workflows/deploy_docs_preview.yml
- disables the dispatch event for private storybook, no longer needs it as latter runs on cron
- update to node 20
- repeat build deployment steps across from preview
- fixes broken 'Edit this page' links
=> Enable Next docs in production

packages/react/src/SubNav/SubNav.test.tsx
Following on from #1003 — tests to prevent regressions
=> Add tests to assert SubNav.SubMenu items' accessibility

.github/workflows/deploy_docs.yml, .github/workflows/deploy_docs_preview.yml
Follows up on #1076 
This updates the production sites (preview + prod), as the other PR only affects local environments.
=> Fix site title in Next docs

apps/next-docs/package.json, package-lock.json
Upgrade Doctocat to latest version
🔗 [Preview link to fixed Hero docs](https://primer-b829b3bc21-26139705.drafts.github.io/brand/components/Hero/react/)
- Upgrade Doctocat to fix live code preview asset loading issues in Hero, Card and VideoPlayer docs
- Fix semantic ordering of docs layout, so that sidebar appears before the main content
Go to the Hero page and verify images are now loading correctly
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
=> Doctocat upgrade to 0.5.8

packages/react/src/Testimonial/Testimonial.test.tsx
Backfills tests for Testimonial component to bring [coverage up to 100%](https://github.com/primer/brand/actions/runs/16293248338/job/46008099945?pr=1107#step:10:227).
- Towards https://github.com/github/primer/issues/5412
=> Add tests for Testimonial component

.github/copilot-instructions.md
Adds Copilot agent instructions to the repo
=> Add Copilot instructions to the project

.changeset/five-goats-march.md, packages/react/src/Accordion/Accordion.test.tsx, packages/react/src/Accordion/Accordion.tsx
Backfills tests for Accordion component to bring coverage up to 100%.
- Towards https://github.com/github/primer/issues/5412
=> Add tests for Accordion component

README.md
=> Fix "getting started" link in top-level README.md
