primer/brand

docs/content/components/FAQ.mdx
docs/content/components/Heading.mdx
docs/content/components/River.mdx
docs/content/components/Text.mdx
docs/content/getting-started/theming.mdx
docs/src/@primer/gatsby-theme-doctocat/components/live-preview-wrapper.js

Removes usage of `<Container>`  in docs code snippets and hoists it into the code snippet decorator.
This removes redundant boilerplate from code snippets and will help remove these changes from https://github.com/primer/brand/pull/69
- added `Container` to  Doctocat code preview
- removed `Container` declarations in all code snippets
- Checking the docs still look okay 🙏 
- There should be no visual regression or changes as it's a like-for-like switch.

Remove Containers from inline code snippets

---

CONTRIBUTING.md
README.md

Fixes NPM badge in readme, which incorrectly references `@primer/brand` as the npm package name. 
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix npm badge in README.md

---

docs/content/components/FormControl.mdx
docs/content/components/Select.mdx
package-lock.json
package.json
src/forms/Checkbox/Checkbox.tsx
src/forms/FormControl/FormControl.stories.tsx
src/forms/Select/Select.stories.tsx
src/forms/form.stories.tsx
src/hooks/useIsomorphicLayoutEffect.ts

Our consumer integration tests are failing in https://github.com/primer/brand/pull/77 because the Select and Checkbox components display runtime errors in both Create React App and Astro.
This _should_ fix it.
- **updated** Select examples in docs and storybook
- **added** useIsomorphicLayoutEffect hook and replaced in Checkbox
- **updated** React type definitions dependency as it was causing typescript errors
- CI tests still passing without visual changes detected
n/a

Fix runtime warnings in Select and Checkbox components

---

src/forms/FormControl/FormControl.test.tsx
src/forms/FormControl/FormControl.tsx

`FormControl` accepts a top-level `id` value, which it propagates down to both the label and inputs. 
Currently, this is prefixed with `FormControl` before being forwarded, which results in the following problems downstream in an application where tests expect the id to be forwarded verbatim.
This PR prevents the prefixing or `for`, `id` and `name` attributes by forwarding the id verbatim, or if an id isn't passed, it will generate a unique id instead per the existing behavior.
- removed prefixing from ids
- hoisted prefixing to parent wrapper instead, in case it's still useful
- updated tests to reflect changes
- Check tests pass
- Code review
- Corresponding [pull request in resources.github.com](https://github.com/github/resources-hub/pull/492), which helped identify this issue.
> …

Fix id and name prefixing in FormControl

---

.storybook/main.js
package-lock.json
package.json

[Storysource](https://storybook.js.org/addons/@storybook/addon-storysource) adds a panel with a code snippet of the story "source" code for easy copy/paste. The source code view depends on the format of the story, and unfortunately isn't compatible with `template.bind()` syntax. However, if we treat "Feature" stories as code snippets and allow the Playground story to use controls, we kind of get the best of both worlds. We might consider investing in our own source code addon that is more consistent.
Closes https://github.com/github/primer/issues/1385
Are we okay with some of the existing stories showing code like this?
- Open the Storybook PR preview deploy
- Navigate to the "Story" tab in the addon panel

Add Storybook Storysource addon

---

.changeset/cyan-geckos-fly.md
packages/react/src/Button/Button.module.css
packages/react/src/Button/Button.stories.tsx
packages/react/src/Button/Button.tsx
packages/react/src/Button/Button.visual.spec.ts

Adding a subtle variant to the Button component.
- **added** subtle variant for button component because it will be used on future marketing pages.
- Review that the variant can be applied correctly and that other variants are not affected.
1. Go to Button story in Storybook
3. Verify that subtle variant behaves as described in the following issue.
- https://www.figma.com/file/BJ95AjraesmRCWsKA013GS/Primer-Brand?node-id=373%3A8028
- https://github.com/github/primer/issues/1417
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Added Subtle Variant to Button

---

.github/workflows/integration_test_astro.yml
.github/workflows/integration_test_cra.yml
.github/workflows/integration_test_nextjs.yml
.github/workflows/integration_test_remix.yml
.github/workflows/release_canary.yml
packages/e2e/integration-tests/nextjs/.eslintrc

End-to-end integration tests for Astro and Next.js were - rather coincidentally - failing at the same time.
This was first detected in PR's, but hasn't impacted main branch yet as it hasn't run the integration tests since its last push.
**This PR fixes the issue and serves as an RCA for what occurred, and how the problem was remediated.**
<table>
<tr>
<th>Date</th>
<th> Event </th>
</tr>
<tr>
<td>26 Oct 2022</td>
<td>Last commit to `main` branch</td>
</tr>
<tr>
<td>27 Oct 2022</td>
<td> Astro release v1.2.0, which includes a breaking change for non-tty users of its CLI package (create astro)</td>
</tr>
<tr>
<td>1 Nov 2022 (~1pm GMT)</td>
<td>Integration test for Astro first observed to fail in a newly created pull request</td>
</tr>
<tr>
<td>1 Nov 2022  (~3pm GMT)</td>
<td> Next.js …

Hotfix and root cause analysis (RCA): Failing integration tests

---

.github/workflows/integration_test_astro.yml
.github/workflows/integration_test_cra.yml
.github/workflows/integration_test_nextjs.yml
.github/workflows/release_canary.yml
package-lock.json

Fixes failing integration tests, which were due to missing cached binaries for cypress. Fixed by manually reinstalling them.

Fixing integration tests

---

.changeset/red-fans-reflect.md
packages/react/src/Button/Button.module.css

Fixes #188.
Applies a `transition: none` rule to `:focus` on the `<Button>` component. This is to ensure that the existing `box-shadow` on `:hover` does not interfere with the the `:focus` `box-shadow`.
- Adds `transition: none` to `.Button:focus`.
- The differences between `<Button>` focus indication on current version, and the changes within this PR.
1. Open up the preview environment for this PR, and proceed to the [docs for `CTABanner`. ](https://primer-0a3811813b-26139705.drafts.github.io/components/CTABanner)
2. Open up the current version of Primer Brand docs and proceed to the [docs for `CTABanner` on our current release build](https://primer.style/brand/components/CTABanner).
3. Go to any example with `<Button>` present, and ensure that component is in "dark" themed mode.
4. …

Button Focus Transition Fix

---

packages/react/src/SubdomainNavBar/SubdomainNavBar.test.tsx
packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx
packages/react/src/Testimonial/Testimonial.tsx

Fixes two issues
1. Allows forwarding a custom class to the root element of the SubdomainNavBar. This is required for app-level customisation and is currently replacing the internal styling completely, which is a bug.
2. Fixed Avatar console warnings around forwardRef, which are appearing in tests and also in the console of apps that use Primer Brand

Fix className forwarding in SubdomainNavBar and Avatar forwardRef error

---

.changeset/serious-crews-arrive-primitives.md
.changeset/serious-crews-arrive.md
.changeset/yellow-clocks-join.md
packages/react/src/Avatar/Avatar.tsx

Fixes Avatar type definitions by correctly forwarding native `img` attributes.
Also split out the changeset for ActionMenu, so that the correct information goes into appropriate changelogs
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix Avatar type definitions

---

.changeset/brown-zebras-smash.md
packages/react/src/SubdomainNavBar/NavigationVisbilityObserver.tsx
packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css
packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css.d.ts
packages/react/src/SubdomainNavBar/SubdomainNavBar.stories.tsx
packages/react/src/SubdomainNavBar/SubdomainNavBar.test.tsx
packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx

Addresses some accessibility issues found in the [a11y eng review of `SubdomainNavBar`](https://github.com/github/primer/issues/1668).
- Removes unneeded `ARIA` usage
- Adjusts some landmarks to reduce verbosity
- Fixes some `aria-expanded` states
This PR should not introduce any style changes. if using a screen reader, test to ensure that states are properly announced (i.e. "more" disclosure, mobile "menu", `combobox`).
1. Go to the component in Storybook
2. Ensure that `aria-expanded` is being set properly on expandable components
3. Observe changes made in "search results" listbox, and landmarks (`role="search"`, `<nav>`)
- https://github.com/github/primer/issues/1668

`SubdomainNavBar` a11y fixes

---

packages/react/src/SubdomainNavBar/SubdomainNavBar.test.tsx
packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx

Removes `console.error` log from `SubdomainNavBar` by adding a check to the `setTimeout` function.
- Adds check to `setTimeout` to confirm container is present
- No `console.error` logs showing up in CI check
- Go to CI step `CI / Install and run tests`
- See if any `console.error` logs are coming from `Run unit tests` step

Removes `console.error` log from test

---

.changeset/loud-eels-perform.md
packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css

Adds additional media query rules to prevent CTA links from not being visible at select viewports and 200% zoom.
Resolves: https://github.com/github/primer/issues/2009
- Adjusts media queries 
- Secondary CTA link stays present at 200% zoom **or** when viewport width is between `768px` and `1023px`
- Ensure navigation links do not overlap when viewport width shrinks
1. Go to the [component on Storybook](https://primer.style/brand/storybook/iframe.html?args=&id=components-subdomainnavbar--playground&viewMode=story)
2. Set browser zoom to 200% ([Chrome](https://support.google.com/chrome/answer/96810?hl=en&co=GENIE.Platform%3DDesktop), [Firefox](https://support.mozilla.org/en-US/kb/font-size-and-zoom-increase-size-of-web-pages#w_zoom-in-and-out-of-a-website))
3. **(Optional)** Set viewport …

Fix zoom issue in `SubdomainNavbar`

---

.changeset/wild-turtles-confess.md
packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css
packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css.d.ts
packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx

Fixes focus order issue when mobile menu is present.
Related: https://github.com/github/primer/issues/1668
- Splits up usage of menu items to handle desktop and mobile menu views
- Focus order when mobile menu is present
- No visual changes are present
1. Open up Storybook environment provided by this PR
2. Open "Mobile Menu" example of `SubdomainNavbar`
3. Expand the mobile menu, and navigate to the menu items via tabbing
- https://github.com/github/primer/issues/1668
- [Focus Order](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html)
<table>
<tr>
</tr>
<tr>
<td align="center">
https://user-images.githubusercontent.com/26746305/234039220-bcb8b286-a026-435f-9354-7617efec5e56.mov
Video showing an example of focus navigation within mobile view of …

Fix focus order for mobile menu in `SubdomainNavbar`

---

packages/react/src/Image/Image.test.tsx
packages/react/src/Image/Image.tsx

Fixing a bug where the `srcSet` prop was only allowed when the `as` prop was used
Removed test related to using srcSet on picture when the sources array should be used instead.
- Ensuring this prop works as expected
- https://github.com/primer/brand/pull/242#issuecomment-1523478707
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Supporting Image SrcSet

---

packages/react/src/CTABanner/CTABanner.module.css

Adjust width property to avoid shrinking when using `Stack` or `Grid` components as wrappers.
- **added** `width: 100%` to `.CTABanner`
- Using `Stack` or `Grid` components on a `CTABanner` works as expected and doesn't shrink the wrapper 
1. Open the CTABanner component in storybook
2. Add `display:flex` to the parent
3. Verify that CTABanner behaves as described in the following issue.
- Slack thread: https://github.slack.com/archives/C04E44ZPNEA/p1683546014522099
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

[CTABanner] Fix container width

---

.changeset/small-hats-itch.md
apps/docs/content/components/Hero.mdx
packages/react/src/Button/Button.tsx
packages/react/src/Hero/Hero.features.stories.tsx
packages/react/src/Hero/Hero.tsx

Adjusts types for `HeroActions` type. 
* Remove `Omit` for `variant` prop
* Fix `leadingVisual` and `trailingVisual` type issue
- Adjusts TS types for `HeroActions`
- The ability to use props stemming from `Button`
- Added story to showcase icon support and `variant` usage
* Ensure no TypeScript errors are present when utilizing props from the [Brand `Button` component](https://primer-5dccbf8f09-26139705.drafts.github.io/components/Button#component-props).

Fix type issues in `Hero`

---

apps/docs/gatsby-config.js
apps/docs/src/@primer/gatsby-theme-doctocat/primer-nav.yml

Similar to https://github.com/primer/design/pull/509 and https://github.com/primer/react/pull/3435
- Updates top-level nav links as described in https://github.com/github/primer/issues/2323
- Updates header to say "Primer Design System / React" instead of "Primer / React"
- Documentation 👁️ : https://primer-798660e1be-26139705.drafts.github.io/

Update header navigation

---

apps/docs/content/components/Label/react.mdx
apps/docs/content/components/Pillar/react.mdx

Add missing `Reviewed for accessibility` labels in docs for `Pillar` and `Label`. 
- **added** a11yReviewed variable in the frontmatter
- Documentation pages for `Pillar` and `Label`
- https://github.com/primer/brand/pull/273
- https://github.com/primer/brand/pull/301
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Add a11yReviewed badges

---

apps/docs/content/components/LogoSuite/react.mdx

- Delete the small variant option on the `required` button for props  to create consistency with other pages
- Changed `label` to be from primer brand
- the other libraries use this version
Fixing the label size for the `required` props.
🔗 [doc](https://primer-55243873a7-26139705.drafts.github.io/)
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix LogoSuite react doc (label size) 

---

apps/docs/content/components/Box/react.mdx
apps/docs/content/components/Heading/react.mdx
apps/docs/content/components/Timeline.mdx
apps/docs/scripts/components-with-animation.js

- Updates the documentation to reflect recent changes to heading scale.
- Adds a note to Box and Timeline pages to indicate that `dir` needs to be set for the component to display correctly. This is because we use logical properties, that are part of the selectors for those components.
- Check wording, grammar, etc
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix documentation for heading, box and timeline

---

.changeset/bright-actors-agree.md
packages/react/src/Accordion/Accordion.module.css

Closes #432 
Removes incorrect click target areas in accordion toggles from appearing above the subsequent content.
First line of the content will no longer open/close the accordion item.
1. Review storybook examples
<table>
<tr>
</tr>
<tr>
https://github.com/primer/brand/assets/13340707/3e1d0a9a-8370-4c44-a95d-e18e7b80cf66
</td>
https://github.com/primer/brand/assets/13340707/10ed90cd-5660-40dd-9b45-e21dbe2152f9
</td>
</tr>
</table>

Fix incorrectly appearing click targets in accordion content

---

.changeset/giant-wasps-check.md
packages/react/src/Card/Card.features.stories.tsx
packages/react/src/Card/Card.module.css

Adds default height to Card to align vertical size when using Grid or Stack components as a wrappers.
- **added** default height 100% to Card
- Cards in the [storybook Stacked example](https://primer-81790c4190-26139705.drafts.github.io/storybook/?path=/story/components-card-features--stacked) are always aligned in different viewports:
- https://github.slack.com/archives/C04E44ZPNEA/p1695744098808819
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

[Card] Add default height 100%

---

apps/docs/content/components/CTABanner/index.mdx
apps/docs/content/components/CTAForm/index.mdx
apps/docs/content/components/FAQ/index.mdx
apps/docs/content/components/Grid/index.mdx
apps/docs/content/components/Heading/index.mdx
apps/docs/content/components/Label/index.mdx
apps/docs/content/components/River/index.mdx

This PR updates image examples in the design guidelines regarding the latest Typographic and border radius scale changes. This affects a list of component like Hero, River, CTABanners, etc.
This is part of the documentation update issue: https://github.com/github/primer/issues/2620
- **updated** `Label` image examples
- **updated** `FAQ` image examples
- **updated** `CTABanner` image examples
- **updated** `CTAForm` image examples
- **updated** `Grid` image examples and layout
- **updated** `Heading` image examples
- **updated** `River` image examples
Documentation is updated with latest site refactor designs. 
Preview: https://primer-e6cc30237b-26139705.drafts.github.io/components/CTABanner
- https://github.com/github/primer/issues/2620
> Please try to provide before and after …

[Site refactor] Documentation update

---

.changeset/export-windowsize-hook.md
.changeset/fix-hero-refs.md
packages/react/src/Hero/Hero.tsx
packages/react/src/index.ts

Adding missing export for `useWindowSize`, which is required for side-by-side recipes. Also backfills missing `forwardRef` references in Hero. 
- Just a code review
n/a

Add lib export for useWindowSize and add forwardRef to hero children

---

.changeset/perfect-mirrors-report.md
packages/react/src/MinimalFooter/MinimalFooter.tsx

Changes the `aria-label` on the GitHub link in the footer.
Solves #387 and https://github.com/github/accessibility-audits/issues/5252
- Changes the `aria-label` on the GitHub link in the footer.
That the `aria-label` matches the visual text (`"GitHub"`)
1. Go to the [minimal footer story](https://primer-0a3609e6d8-26139705.drafts.github.io/storybook/?path=/story/components-minimalfooter--default)
2. Find the `GitHub` mark in the footer and right-click -> Inspect Source
3. Ensure that the `aria-label` is `GitHub`.
- https://github.com/github/accessibility-audits/issues/5252
- #387
N/A. No visual changes.

Update aria-label on GitHub link

---

apps/docs/content/components/SectionIntro/index.mdx

- Changes images for the SectionIntro guidelines page.
- Added emphasized text option with image and brief guidelines.
🔗 https://primer-176d4c1f8e-26139705.drafts.github.io/components/SectionIntro
@nsolerieu I took the liberty to add what I think is a good basic description of how the emphasized text variation should be used and an image with content from the Enterprise landing page. 
Adding here for visibility: 
Section intro allows for only one portion of the heading to be highlighted. Use strategically to highlight key ideas and guide effectively through a story.

SectionIntro – Image updates and minor changes

---

.changeset/light-kings-clap.md
packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx

Keyboard nav around the Subdomain Navbar now correctly loops after you get to the end of the menu
Fixes #369 and https://github.com/github/accessibility-audits/issues/5232
**Updated** SubdomainNavbar
- That keyboard navigation around the SubdomainNavBar works correctly
1. Go to the SubdomainNavbar story (one of the mobile ones)
1. Open the sandwich menu
1. Use the tab key to navigate the menu items
- https://github.com/github/accessibility-audits/issues/5232
- #369 
<table>
<tr>
</tr>
<tr>
https://github.com/primer/brand/assets/12260694/a5158796-cbe8-40b0-b959-0803d74e0cf3
</td>
https://github.com/primer/brand/assets/12260694/08fa7260-488c-4261-aa06-797bcf530 …

SubdomainNavbarMenu Focus Trapping

---

packages/react/src/Accordion/Accordion.module.css

Part of fixing https://github.com/primer/brand/pull/486
Removes a stray line of CSS that shouldn't be there. Found during dotcom regression test. This is a product token, which is why it doesn't appear in our visual tests or Storybook, only in dotcom.
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Remove erroneous style in accordion

---

apps/docs/content/components/Bento.mdx

Part of https://github.com/github/primer/issues/2746#issuecomment-1792503715
Promotes Bento to alpha following successful a11y review
- Promotes Bento to `alpha`
- Adds note about source order, which applies when bento is used in responsive configurations
- Marked as a11y reviewed
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
Message about source order:

Update bento docs for indicate a11y review passed, and promote to alpha

---

packages/react/src/forms/TextInput/TextInput.stories.tsx

Changing props from Objects to JSX in #489, TextInput visuals seem to have been missed in the stories.
Fixes stories for TextInput
Do the icons now appear correctly in the TextInput stories
1. Go to the TextInput storybook
2. Enable the leading and trailing visuals.
3. See that they now work.
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Visuals in TextInput props should also be components

---

.changeset/perfect-boxes-fetch.md
packages/design-tokens/src/tokens/functional/components/image/base.json
packages/react/src/Image/Image.module.css

Part of https://github.com/github/primer/issues/2097
Tokens renamed:
--brand-Image-ratio-custom → --brand-image-aspectRatio
In order for this name to make sense/fit our convention, I modified the CSS to reference the token and then reset the value for each prop.

Rename `Image` token + refactor CSS

---

.changeset/dry-news-dress.md
.changeset/lucky-pugs-agree.md
packages/react/src/Hero/Hero.tsx

Minor change that resolves #528 - allowing users to add custom class names to the `HeroDescription` component
- **added** `{...rest}` to `HeroDescription` to allow for custom class names to be used, this pattern is being used in `HeroHeading`, `HeroImage` etc.
One thing to consider is that when a custom class name is being used it will remove the `Hero-description` styles, this is existing behaviour on the `HeroHeading` therefore isn't a regression. 
1. Run Storybook
1. Modify the default `Hero.stories.tsx` file and include a `className` on the `HeroDescription` component.
1. Open the Hero story on storybook, inspect element and see class added to the hero description.

Resolves #528 - spread props on HeroDescription

---

apps/docs/content/components/SectionIntro/index.mdx

Adds content length guidance and do's and don'ts for section intro.
[Docs preview](https://primer-72c54b3967-26139705.drafts.github.io/components/SectionIntro)

Add interface guidelines for section intro content length

---

apps/docs/content/components/River/index.mdx

Adds content length guidance and do's and don'ts for river breakout.
[Docs preview](https://primer-e985c93047-26139705.drafts.github.io/components/River#river-breakout)

Add interface guidelines for river breakout content length

---

.changeset/gentle-wolves-vanish.md
packages/design-tokens/src/tokens/functional/components/footer/colors.json
packages/react/src/MinimalFooter/MinimalFooter.module.css
packages/react/src/MinimalFooter/MinimalFooter.module.css.d.ts
packages/react/src/MinimalFooter/MinimalFooter.tsx

Solves https://github.com/github/primer/issues/3063
[Storybook examples](https://primer-3ecc927f1b-26139705.drafts.github.io/storybook/?path=/story/components-minimalfooter-features--dark-theme)
_Please note: this temporary solution uses CSS filters to work around a limitation in the current implementation of MinimalFooter. The social icons are loaded in an `img` tag, preventing direct fill color changes in CSS. In a future PR, we will inline SVG icons to set the `hover` state color directly._

Add hover states to social icon links in MinimalFooter

---

apps/docs/content/components/Label/index.mdx

Updated the images containing gradient labels to match the latest [changes](https://github.com/github/primer/issues/3084#event-12130265516) to text color.

Update label docs images 

---

.changeset/long-lions-cough.md
packages/react/src/IDE/IDE.module.css

When we tried to update `@primer/react-brand` to 0.33.0, we got the following error in our CI output when trying to build CSS for the package:
```
Error: "+" and "-" must be surrounded by whitespace in calculations.
17134    font-size: calc(var(--base-size-12) -1px) !important;
^
@primer/react-brand/lib/css/main.css 17134:39  @import
app/assets/stylesheets/primer-brand.scss 9:9   root stylesheet
```
Added a single space character after the minus sign
1. Build the CSS using `dartsass`
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Add a space after the minus sign so that CSS can be built successfully

---

.changeset/soft-chicken-march.md
packages/react/src/SubNav/SubNav.module.css
packages/react/src/SubNav/SubNav.stories.tsx

Changes to SubNav styling:
* [`packages/react/src/SubNav/SubNav.module.css`](diffhunk://#diff-1edfafbe6a934fda2b154695158be5930bbf9793d69717351c878dfccdd26f7aL129-R129): Updated the CSS selectors for `.SubNav__links-overlay--open .SubNav__link[aria-current]`, `.SubNav__link:hover *`, `.SubNav__link[aria-current]` and `.SubNav__link[aria-current] .SubNav__link-label::after` to exclude `SubNav` links with `aria-current` set to "false" from active link styling. [[1]](diffhunk://#diff-1edfafbe6a934fda2b154695158be5930bbf9793d69717351c878dfccdd26f7aL129-R129) [[2]](diffhunk://#diff-1edfafbe6a934fda2b154695158be5930bbf9793d69717351c878dfccdd26f7aL223-R223) [[3]](diffhunk://#diff-1edfafbe6a934fda2b154695158be5930bbf9793d69717351c878dfccdd26f7aL245-R245)
Changes to SubNav stories:
* …

Exclude Subnav links with aria-current set to "false" from active link styling

---

apps/docs/content/getting-started/animation.mdx
package-lock.json

- Fix error on Animation page (in production) of docs caused by incorrect icon usage.
- Update `package-lock.json` with latest primer versions (`0.34.0`)
1. Open updated Animation page in docs ([here](https://primer-1a2af1221e-26139705.drafts.github.io/getting-started/animation))
1. Verify that the _Cards and staggering_ example doesn't show a red error message
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix Animation docs page

---

.changeset/fast-rice-switch.md
packages/react/src/AnchorNav/AnchorNav.test.tsx
packages/react/src/AnchorNav/AnchorNav.tsx
packages/react/src/AnchorNav/useExpandedMenu.ts

Resolves an issue where the focus was trapped on mobile when using the `AnchorNav` component. This PR adds a new attribute to the `span` element in the `AnchorNav` component to allow the focus to move forward when the tab key is pressed.
- `data-forward-focus` attribute added to span which wraps `AnchorNav` actions. The name is arbitrary, but it is used to determine if the focus should instead be forwarded to the element's first child
- Fixes a few minor typos in the `AnchorNav` test file
- DOES NOT add any tests for the focus fix. I couldn't get tabbing and focus tracking to work correctly inside the unit tests unfortunately. 
- Are you happy with the `data-forward-focus` approach?
- Check that you're able to tab from any link in the `AnchorNav` to the first of the actions
- #608 
> …

Fix AnchorNav focus bug

---

.changeset/soft-mugs-live.md
packages/react/src/AnchorNav/AnchorNav.tsx
packages/react/src/AnchorNav/useExpandedMenu.ts

Replace arrow key navigation with standard tab order navigation for the AnchorNav component.
- Ensure you can navigate through an AnchorNav using <kbd>Tab</kbd> and <kbd>Shift</kbd> + <kbd>Tab</kbd> keys
1. Open the AnchorNav component in Storybook
2. Resize your viewport to see the mobile AnchorNav
3. Use the <kbd>Tab</kbd> key to navigate through the links
4. Use the <kbd>Shift</kbd> + <kbd>Tab</kbd> to navigate backwards
- [Link to updated AnchorNav Storybook](https://primer-02373c4008-26139705.drafts.github.io/storybook/?path=/story/components-anchornav-features--narrow-view)
- https://github.com/github/accessibility-audits/issues/7852
https://github.com/user-attachments/assets/1b4aa8b8-9614-4396-8fda-be9e66335ded

use default tab order for AnchorNav

---

.changeset/long-ties-burn.md
package-lock.json
packages/react/src/FAQ/FAQGroup.tsx

I gated the focus logic via the initialRender ref to move focus on arrow navigation. However, the Alloy actually triggers the render of the FAQGroup component, which causes the initialRender ref to be set to false. This causes the autofocus to the first FAQGroup element and the page is scrolled to it.
This PR changes the logic to gate the focus logic via the hasInteracted state instead of the initialRender ref. This way, the focus logic is only triggered after the user has interacted with the FAQGroup component.
**This issue is only present in development environment** probably due the Alloy dev setup...
- **updated** `FAQGroupProps` type to include `hasInteracted` state because the focus logic is gated via the `hasInteracted` state instead of the `initialRender` ref.
This can only be …

Fix FAQGroup autofocus with Alloy issue

---

apps/docs/src/components/content/ColorThemePicker.js
apps/storybook/.storybook/preview.js

- Fix colour mode label in Storybook
- Fix theme selector on Color primitives page
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Tiny docs bugs

---

.changeset/happy-ducks-jump.md
packages/design-tokens/src/tokens/functional/components/logosuite/colors.json
packages/react/src/LogoSuite/LogoSuite.module.css

Style `LogoSuite` logos differently depending on their format. Images using the `<img>` tag will be styled with a CSS filter, whereas inline SVGs will be styled with CSS fill.
Reverts commit 9724866560efa2f85dd8dde0966f0a5d12503ade 
- Added filters to `LogoSuite` colors.json
- Modified `LogoSuite.module.css` to use CSS fill for SVGs and CSS filter for raster logos 
- Ensure there are no visual regressions, and that the colours of the monochrome raster logos are consistent with their SVG counterparts.

Only use CSS filter for raster logos, not SVGs

---

apps/docs/content/components/ActionMenu.mdx
apps/docs/content/components/Breadcrumbs.mdx
apps/docs/content/components/Card/react.mdx
apps/docs/content/components/Checkbox/react.mdx
apps/docs/content/components/FormControl.mdx
apps/docs/content/components/Grid/react.mdx
apps/docs/content/components/Heading/react.mdx
apps/docs/content/components/IDE.mdx
apps/docs/content/components/Label/react.mdx
apps/docs/content/components/LogoSuite/react.mdx
apps/docs/content/components/MinimalFooter.mdx
apps/docs/content/components/OrderedList/react.mdx
apps/docs/content/components/Pagination.mdx
apps/docs/content/components/Pillar/react.mdx
apps/docs/content/components/Prose.mdx
apps/docs/content/components/Radio/react.mdx
apps/docs/content/components/Select.mdx
apps/docs/content/components/Stack/react.mdx
apps/docs/content/components/SubdomainNavBar.mdx
apps/docs/content/components/Text/react.mdx
apps/docs/content/components/Textarea.mdx
apps/docs/content/components/Tooltip.mdx
apps/docs/content/components/UnorderedList/react.mdx

Fixing any broken links, and updating pointing all Storybook links to the Playground story if available.
This issue has arisen because locally the links on the docs site do not point to the local Storybook instance, so it's a pain to manually check them (copy/pasting the story ID). I've created an issue to explore this #625
For this PR I hacked the component in doctocat that renders the storybook link to point towards my local Storybook server.
in `apps/docs/node_modules/@primer/gatsby-theme-doctocat/src/components/storybook-link.js`:
```js
const storybookHref =
process.env.NODE_ENV === 'development'
? `http://localhost:6006/${href.slice(href.indexOf('/brand/storybook/') + 17)}`
: href
```
- It seemed there were about as many links to the default story as to the playground story. I went …

Fix Storybook links

---

.changeset/perfect-wasps-speak.md
apps/docs/content/components/FAQ/react.mdx
packages/react/src/FAQ/FAQGroup.test.tsx
packages/react/src/FAQ/FAQGroup.tsx

Adds `tabAttributes` prop to `FAQGroup` component. This prop is used to set arbitrary attributes on the tabs rendered by the `FAQGroup` component.
For example, the below code will add `data-analytics="tab-0"` to the first tab and `data-analytics="tab-1"` to the second tab.
```tsx
<FAQGroup
tabAttributes={(children, index) => ({
'data-analytics': `tab-${index}`,
})}
>
<FAQGroup.Heading>Frequently asked questions</FAQGroup.Heading>
<FAQ>
<FAQ.Heading>Using GitHub Enterprise</FAQ.Heading>
<FAQ.Item>...</FAQ.Item>
<FAQ.Item>...</FAQ.Item>
<FAQ.Item>...</FAQ.Item>
</FAQ>
<FAQ>
<FAQ.Heading>About GitHub Enterprise</FAQ.Heading>
<FAQ.Item>...</FAQ.Item>
<FAQ.Item>...</FAQ.Item>
<FAQ.Item>...</FAQ.Item>
</FAQ>
</FAQGroup>
```
- Adds `tabAttributes` prop to FAQGroup
- Adds `tabAttributes` tests to …

Add `tabAttributes` prop to `FAQGroup` component

---

apps/storybook/.storybook/main.js
apps/storybook/.storybook/preview.js

Some tweaks to make Storybook easier and more intuitive to navigate, based on the audit in https://github.com/github/primer/issues/3635
- Components in the sidebar are sorted alphabetically - previously they were sorted by load order, so it was mostly alphabetical but some nested folders like forms and river were at the bottom
- Components always show Default, then Playground, then sub-folders (examples + feature stories)
- Examples and feature stories are ordered in the order they're written in the file
- Moved Controls to be the first panel in addon sidebar so it opens automatically (previously was a11y panel)
- Removed Links addon (unused and cluttering sidebar)
[PRC has a more complex sorting algorithm](https://github.com/primer/react/blob/%40primer/react%4036.26.0/packages/react/.stor …

Improve Storybook UX

---

.changeset/sixty-jobs-perfectly.md
packages/react/src/forms/FormControl/FormControl.test.tsx
packages/react/src/forms/FormControl/FormControl.tsx

Resolves https://github.com/primer/brand/issues/666
- Forwards `name` props correctly to Select elements that are used inside a FormControl to match other input types
- Adds test coverage 
1. Review live documentation, and add a name attribute to Select
1. Use inspector to verify the name attribute has been set on the Select correctly
n/a

fix prop forwarding to Selects inside FormControl

---

apps/docs/content/components/VideoPlayer.mdx
apps/docs/gatsby-node.js
packages/react/src/VideoPlayer/VideoPlayer.features.stories.tsx
packages/react/src/VideoPlayer/VideoPlayer.stories.tsx
packages/react/src/recipes/SolutionTemplates/SolutionPage/SolutionPage.tsx
packages/react/src/river/RiverStoryScroll/RiverStoryScroll.features.stories.tsx

There are currently some issues with the static directories in both the preview/production Storybook and the docs which result in assets not loading correctly in certain environments. The only component which consumes these assets is `VideoPlayer`, so the issue hasn't been particularly noticeable up to now.
This PR resolves those issues and allows us to pull static assets from the asset directory of the current application, without having to pull all assets from the production site, as we were doing before.
> ⚠️ NB This PR uses the `cp` method on Node's `fs` API — in development only — to move the docs assets into the expected directory.  The `cp` method was added in Node 20, so this PR won't work on older versions of Node. If that's an issue, we can use a different method to move the …

Fix static assets dir in preview/production Storybook and docs

---

.github/workflows/integration_test_remix.yml
packages/e2e/integration-tests/fixtures/KitchenSink.tsx
packages/e2e/integration-tests/fixtures/index.esm.ts
packages/e2e/integration-tests/remix.run/root.tsx
packages/e2e/integration-tests/remix.run/vite.config.ts

Fixes failing integration test for Remix
- Is the workflow passing in the Checks?
Fixed:

Switch remix integration test template to default

---

.changeset/little-comics-pull.md
packages/design-tokens/scripts/style-dictionary.js
packages/design-tokens/src/tokens/functional/animation/base.json
packages/design-tokens/src/tokens/functional/components/card/base.json
packages/design-tokens/src/tokens/functional/components/eyebrow-banner/eyebrow-banner.json
packages/design-tokens/src/tokens/functional/components/faq/base.json
packages/design-tokens/src/tokens/functional/components/ide/base.json
packages/design-tokens/src/tokens/functional/components/section/section.json
packages/design-tokens/src/tokens/functional/components/statistic/base.json
packages/design-tokens/src/tokens/functional/components/sub-nav/base.json
packages/design-tokens/src/tokens/functional/components/timeline/base.json
packages/design-tokens/src/tokens/functional/components/video-player/base.json
packages/design-tokens/src/tokens/functional/size/border.json
packages/design-tokens/src/tokens/functional/size/size.json
packages/design-tokens/src/tokens/functional/typography/typography-responsive.json
packages/react/src/VideoPlayer/VideoPlayer.module.css

Replace custom transform with upstream equivalent

Use dimension/px transformer instead of custom

---

packages/react/src/river/RiverStoryScroll/RiverStoryScroll.tsx
packages/react/src/river/RiverStoryScroll/RiverStoryScrollResponder.tsx
packages/react/src/river/RiverStoryScroll/RiverStoryScrollTracker.tsx

Lightly refactors `RiverStoryScroll` and moves the check that children are `River` components to TypeScript.
If consumers want to pass a component that isn't a River — for example a custom component which wraps `River` — then they will need to suppress a TypeScript error (for example, using a `@ts-expect-error` comment).
- Uses TypeScript to enforce that `RiverStoryScroll` children are `River` components
- Small refactoring of `RiverStoryScroll` to remove a few unused variables, remove some nesting, and remove some type assertions
- Check that all of the `RiverStoryScroll` stories still work as expected
- https://github.com/primer/brand/issues/745

Enforce `RiverStoryScroll` children are Rivers using types

---

.eslintrc.js
packages/react/src/river/River.figma.tsx

Adds basic Figma code connect to the River component. 
- Adds Figma code connect file for the River component
- Disables `i18n-text/no-en` in Figma code connect files to support some Figma layer names
- Test River examples in dev mode on the `main` branch in Figma.

Add Figma code connect forn River component

---

.changeset/ninety-taxis-lick.md
packages/react/src/Hero/Hero.tsx

Fixes a bug where passing a `className` to `Hero.Label` or `Hero.Eyebrow` would replace the default class.
1. Pass a `className` prop to `Hero.Label` or `Hero.Eyebrow`
1. Ensure that the default class is not replaced when a `className` is passed
- https://github.com/primer/brand/issues/757

Use clsx to combine HeroLabel and HeroEyebrow classnames

---

.changeset/lovely-rocks-bathe.md
packages/react/src/river/river-shared.module.css

Fixes a layout issue with RiverBreakout cta when the `trailingComponent` is taller and adds  spacing on smaller viewports.
- [StoryBook](https://primer-3355950bee-26139705.drafts.github.io/brand/storybook/?path=/story/components-riverbreakout--default)
- Solves https://github.com/github/primer/issues/3939
- Fixes https://github.com/github/primer/issues/3940

Improve RiverBreakout spacing

---

package-lock.json
package.json

As per our [Accessibility Automation Scorecard](https://catalog.githubapp.com/services/primer/scorecards/accessibility-automation), we need to update `eslint-plugin-github` to the latest version to ensure that our codebase is up-to-date with the latest accessibility standards.
- Update `eslint-plugin-github` to the latest version
- Ensure that linting jobs in the CI pass 
- [Accessibility automation scorecard](https://catalog.githubapp.com/services/primer/scorecards/accessibility-automation)

update eslint-plugin-github to latest

---

.changeset/curly-readers-poke.md
.changeset/forty-lamps-applaud.md

Removes  @primer/brand-e2e` changes from changesets.
These were added in previous PRs (#776, #779) as I had modified the `KitchenSink` fixture, but the changesets aren't actually required.

Remove @primer/brand-e2e changes from changesets

---

packages/react/src/river/river-shared.module.css

Fixes a regression in River that is blocking the next release https://github.com/primer/brand/pull/763
- Ensures the new internal content padding is only applied on `large` viewports and above.
1. Code review
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Hotfixes for 0.41.0 RC (continued)

---

.github/workflows/integration_test_nextjs.yml

Next.js GA release via create-next-app now uses the React v19 RC, which falls outside of our SemVer scope for React (<v20) 😕. Workaround for now is to use legacy peer deps flag, as the the issue is exclusive to Next.

Fixing next.js integration test 

---

.changeset/gentle-bulldogs-live.md
packages/react/src/Link/Link.module.css

Resolves https://github.com/primer/brand/issues/806
Increases width of underline on the `Link` component on hover interaction. See before and after videos below.
- Ensure that the underline extends to end of text label
1. Use the Storybook examples
-
-
<table>
<tr>
</tr>
<tr>
https://github.com/user-attachments/assets/a2c5b0f0-4d47-4495-9400-30abfd3928e6
</td>
https://github.com/user-attachments/assets/4e110a0c-55c9-4e5b-85d1-4b9a67c0f5d4
</td>
</tr>
</table>

Expand Link underline to full width

---

packages/react/src/CTABanner/CTABanner.tsx

Resolves regression to CTA banner in latest smoke test https://github.com/primer/brand/pull/807

Fix broken default bgcolor value in CTA Banner

---

.changeset/blue-ligers-repeat.md
.changeset/chilly-ducks-brush.md
package-lock.json
packages/react/package.json
packages/react/webpack.config.js

Addresses multiple issues in the compiled stylesheet, including:
- Removal of escaped characters in selectors where modern CSS features like `:has` are used
- Switched to use CSS Logical Properties in compiled output, which is both necessary to fix the above and is now worth doing as the feature is widely available in modern browsers.
**Compiled CSS output size is now 9% lower than before.**
Fixes https://github.com/primer/brand/issues/823
- Updates relevant postcss dependency in order to prevent rewriting of `:has` selectors. Previous versions are deprecated, so an upgrade was needed.
- Adds rule to preserve source usage of `:has` and logical properties
- Diff the current production bundle with the canary equivalent
1. Copy [this](https://unpkg.com/@primer/react-brand@latest/lib/css/main. …

Updates to compiled stylesheet

---

apps/docs/content/components/BreakoutBanner/react.mdx

Updates the BreakoutBanner documentation to include information on the leading visual accessible label. As the leading visual shouldn't be used for decorative imagery ([source](https://primer.style/brand/components/BreakoutBanner#leading-visuals)) I think it's safe to say that an accessible label should _always_ be provided.
[You can view the updated docs here
](https://primer-ed55036b48-26139705.drafts.github.io/brand/components/BreakoutBanner/react#leading-visual)
- Closes https://github.com/github/primer/issues/3845

Update BreakoutBanner docs information on leading visual accessible label

---

.changeset/kind-comics-tickle.md
packages/react/src/AnchorNav/AnchorNav.test.tsx
packages/react/src/AnchorNav/AnchorNav.tsx

Following the recommendation in the related issue ([here](https://github.com/github/primer/issues/3756)), this PR removes the `aria-label` attribute from the `AnchorNav` toggle button in favour of visually-hidden text.
I confirmed this behaviour with Patrick [over Slack](https://github.slack.com/archives/C0FSWLQ0Y/p1732884521386289?thread_ts=1732710967.237599&cid=C0FSWLQ0Y) too.
- Make sure you're happy with the recommended approach
- Closes https://github.com/github/primer/issues/3756
-

Remove aria-label from AnchorNav toggle button in favour of visually-hidden text

---

.changeset/good-fishes-yawn.md
packages/react/src/Tooltip/Tooltip.tsx

Adds a small (200ms) delay to the closing of the Tooltip.
This is to allow users to more easily move their cursor over to the contents of the tooltip.
- Make sure you're happy with the timeout. I had a play around with it and 200ms felt like a good balance.
1. Look at the Tooltip stories
1. Mouse over the trigger
1. Move the mouse to the contents of the Tooltip
1. Note that the tooltip doesn't close as soon as the mouse leaves
- Closes https://github.com/github/primer/issues/3803

Add a small delay to closing of Tooltip

---

apps/docs/content/components/FormControl.mdx

Primer best-practise dictates that forms submitted with invalid values should automatically move focus to the first invalid input on submit. This PR highlights that fact in the docs and updates our _Validation_ example to demo this. It also removes live validation that runs on change and replaces it with validation that runs on submit.
- Check you're happy with the wording, as well as the example
1. View the _Validation_ section of the _Form control_ page in the docs.
1. Submit the form with an invalid value.
1. Check that the invalid input receives focus.
- Closes https://github.com/github/primer/issues/3760
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Update docs form validation example to demonstrate best-practise when submitting a form in an invalid state

---

.changeset/sour-numbers-pretend.md
packages/react/src/forms/Select/Select.module.css
packages/react/src/forms/Select/Select.module.css.d.ts
packages/react/src/forms/TextInput/TextInput.module.css
packages/react/src/forms/Textarea/Textarea.module.css

Fixes a bug where TextInput, TextArea, and Select components expand to the width of their parent FormControl's validation message.
https://github.com/user-attachments/assets/8a7b6730-308e-4a9d-9409-93f0fbf2c7a5
- Resolve bug in TextInput, TextArea, and Select components
- Remove some redundant CSS from Select component

Fix TextInput, TextArea, and Select width bug

---

.github/workflows/ci.yml
.github/workflows/figma_connect_publish.yml
.github/workflows/integration_test_astro.yml
.github/workflows/integration_test_cra.yml
.github/workflows/integration_test_nextjs.yml
.github/workflows/integration_test_remix.yml
.github/workflows/ui_test_accessibility.yml
.github/workflows/ui_test_primitives_diff.yml
.github/workflows/update_visual_snapshots.yml
.github/workflows/visual_test_storybook.yml

Upgrades our `actions/cache` workflow dependencies ahead of their [upcoming deprecation](https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/)

Upgrade actions/cache workflow dependencies to v4

---

packages/react/src/PricingOptions/PricingOptions.test.tsx

Adds a test to verify that PricingOptions renders the markup of its items in the correct, accessible order. Follow up of #812.

Add test for PricingOptions markup order

---

.changeset/long-nails-rest.md
packages/react/src/SubNav/SubNav.module.css
packages/react/src/SubNav/SubNav.module.css.d.ts
packages/react/src/SubNav/SubNav.tsx

Follow up to #824 
The heading separator in SubNav now uses CSS to handle visibility instead of JS. This fixes the delayed loading issue observed in dotcom, which doesn't happen in Storybook.
- Removed the conditional JS-based logic for making the separator appear
- Added new CSS class to hide the separator when active labels aren't needed. This replicates the same behaviour that was previously applied in JS.
<table>
<tr>
</tr>
<tr>
https://github.com/user-attachments/assets/053bc728-694a-459c-abc9-cc60d39e25fc
</td>
https://github.com/user-attachments/assets/8838ae55-7dbd-4c35-a6ad-bcdc260b12ab
</td>
</tr>
</table>

Fixed delayed appearance of heading separator in SubNav

---

.github/release_template.md

- Updates the contact page link
```diff
- `/contact-sales`
+ `/enterprise/contact`
```
- Adds `/home`
- Reorders links to group similar paths

Update list of pages in release template

---

.github/workflows/integration_test_remix.yml

Fixes Remix integration test
For posterity, it was failing because the latest version of the CLI automatically initalized git in a sub directory and attempted to make an initial commit but without an active SSH agent this isn't possible inside a GitHub action.
Fixed by removing git initialization, which isn't necessary in an ephemeral end-to-end test.

Fix remix integration test

---

.changeset/strange-cooks-crash.md
packages/react/src/Footnotes/Footnotes.module.css

Added a static `scroll-margin-top` to `Footnote.Item`. This allows a small (100px) amount of space to be present between the top of the viewport and the `Footnote.Item` when it is navigated to.
- Are you happy with the change, and the 100px value?
1. Open [the "return links" example in the Footnotes docs](https://primer-29177d11bf-26139705.drafts.github.io/brand/components/Footnotes/react#citations-with-return-links)
1. Click the number _[1]_
1. Observe that the associated footnote is scrolled to with an offset of 100px
- Closes https://github.com/github/primer/issues/4669
https://github.com/user-attachments/assets/1b76eb42-4453-42af-bf97-cbf36845b830

Add a static scroll-margin-top to a footnote item

---

apps/docs/content/components/CheckboxGroup/react.mdx
apps/docs/content/components/RadioGroup/react.mdx
packages/react/src/forms/CheckboxGroup/CheckboxGroup.examples.stories.tsx
packages/react/src/forms/RadioGroup/RadioGroup.examples.stories.tsx

Updates the inline `CheckboxGroup` and `RadioGroup` examples to reflow on narrow viewports.
There's quite a large row gap between lines. This could be solved by adding `style={{ rowGap: 'var(--base-size-8)' }}` to the `Stack` used in the example. Let me know if that would be preferred.
- Closes https://github.com/github/primer/issues/4672
- Closes https://github.com/github/primer/issues/4673
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>
Having to add an inline style to the example isn't ideal, but without it the rowGap is way too big

Allow inline ControlGroup examples to reflow

---

apps/docs/content/components/SubNav.mdx

Adds a vertical scroll to the _anchor-based submenu_ example in the docs. Previously, the anchor-based submenu was never visible due to the lack of scroll on the example.
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Add scrolling to SubNav docs example

---

.github/workflows/deploy_docs.yml
.github/workflows/deploy_docs_preview.yml
.github/workflows/deploy_docs_preview_forks.yml
.github/workflows/release.yml

Fixes failing prod deployment by updating our reusable workflow versions. We were using an old version that relied on a now deprecated dependency [actions/upload-artifact@v3](https://github.com/actions/upload-artifact)
Edit: also fixes preview deployments, which began failing for the same reasons

Fix failing prod deployment

---

.changeset/kind-years-repair.md
packages/react/src/ActionMenu/ActionMenu.test.tsx
packages/react/src/ActionMenu/ActionMenu.tsx

Removes check for truthiness in `handleItemSelection` in `ActionMenu.tsx` to allow falsy values to trigger item selection callback.
- `ActionMenu.tsx`: Removed check for truthiness in `handleItemSelection` to allow falsy values to trigger item selection callback.
- `ActionMenu.test.tsx`: Added a test to assert that falsy items can be selected
1. Open [the ActionMenu Docs](https://primer-f49b2ea768-26139705.drafts.github.io/brand/components/ActionMenu)
2. Edit the first example to set one of the values to `""`
3. Open the ActionMenu and click on the item associated with that value
4. Observe that the `onSelect` callback is called and triggers an alert.
- 🔗 [Link to docs](https://primer-f49b2ea768-26139705.drafts.github.io/brand/components/ActionMenu)
- Closes #906

ActionMenu falsy value bugfix

---

apps/docs/content/components/Card/react.mdx
apps/docs/content/components/Section/react.mdx

- Updated Section example to use a background colour with sufficient contrast
- Improved styling of torchlight Card example in docs on very small (320px) viewports
- Just check you're happy with the changes
- Take a look at relevant sections in the Section docs, and the Card docs.
- Towards https://github.com/github/accessibility-audits/issues/10394
- Towards https://github.com/github/accessibility-audits/issues/10368
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Docs accessibility fixes

---

.changeset/fluffy-dodos-perform.md
packages/react/src/Card/Card.module.css
packages/react/src/Card/Card.module.css.d.ts
packages/react/src/Card/Card.tsx

Fixes a bug where Card components would need to be tapped twice in iOS Safari to trigger navigation. The first click would, if fast enough, only trigger the hover state. The second click would then perform the navigation.
- Remove mouseenter/exit event listeners from Card component
- Use CSS to trigger the arrow expansion on hover
- Test in iOS Safari — make sure that you can navigate to the associated `href` with a single click on the Card component
1. Open the Docs or Storybook on iOS Safari
2. Navigate to a Card component
3. Quickly tap the Card
4. Ensure that you are navigated to the page with only a single tap
- Closes https://github.com/primer/brand/issues/933

Fix iOS Safari Card component double-tap bug

---

apps/docs/content/components/CTABanner/react.mdx

This patch updates the docs of the CTA banner to accurately reflect current defaults in the code. 
- **updated** documentation for CTA Banner because it did not accurately reflect a default value.
N/A
N/A 
N/A
N/A

update cta banner doc to use correct default

---

apps/docs/content/components/SectionIntro/react.mdx

This updates `Hero.Label` to `SectionIntro.Label`.

Update SectionIntro documentation typo for label

---

.github/release_template.md

Update release template URLs
- Replace `/features/copilot/getting-started` with `/features/copilot/tutorials` as it redirects
- Replace `/enterprise/advanced-security` with `/security/advanced-security` as it redirects
- Remove `/solutions/devops` as it redirects to `/solutions/use-case/devops`, which is already listed
- Remove duplicated (and incorrect) articles URLs.

Update release template URLs

---

.changeset/friendly-tomatoes-dance.md
apps/docs/content/components/PricingOptions.mdx
packages/react/src/PricingOptions/PricingOptions.tsx

Part of https://github.com/github/primer/issues/4785
PricingOptions.Label types now extend the base Label for more accurate type checking.
1. Code review
1. Check before/after screenshots
1. Try it?
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix type definitions for PricingOptions.Label

---

apps/next-docs/content/index.tsx

Fixes homepage card links on Next site
🔗  [Preview link](https://primer-e19ada8d4e-26139705.drafts.github.io/brand/next/)
1. [Go here ](https://primer-e19ada8d4e-26139705.drafts.github.io/brand/next/)and click the cards on the homepage
1. Verify they navigate to correct locations

Fix homepage card links

---

.changeset/calm-countries-explain.md
packages/react/src/SubNav/SubNav.test.tsx
packages/react/src/SubNav/SubNav.tsx

Close hovered `SubNav.SubMenu` on <kbd>Escape</kbd>
- Added a test to verify behaviour
- Explicitly hide collapsed submenu children with `aria-hidden`
- Create utilities for managing submenu state
- Close hovered submenu on <kbd>Escape</kbd> key press
- Check that a hovered submenu can be closed with the <kbd>Escape</kbd> ke
- Closes https://github.com/github/primer/issues/4677

Close hovered `SubNav.SubMenu` on Escape

---

apps/docs/content/components/SubNav.mdx
apps/next-docs/content/components/SubNav/index.mdx

Add documentation to `SubNav` anchor variant to communicate the requirement for individual items to fit within a 320px-wide viewport to conform with WCAG 1.4.10 Reflow given our [additional guidance](https://github.com/github/accessibility-audit-guide/blob/main/web/WCAG/1.4.10%20Reflow.md#additional-guidance)
- Closes https://github.com/github/primer/issues/4678
-

Update `SubNav` docs to communicate a11y requirement

---

.changeset/empty-rockets-kneel.md
packages/react/src/SubNav/SubNav.tsx

Fix a bug where narrow-viewport `SubNav.SubMenu` links were hidden from screen readers.
This bug was introduced in https://github.com/primer/brand/pull/989
- Removes `aria-hidden` from `SubNav.SubMenu` links when `isLarge` is `false`.
- Check that `aria-hidden` is `false` on mobile viewports.
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix bug where SubNav Submenu links were hidden from screen readers

---

apps/docs/content/components/Select.mdx
apps/docs/content/components/TextInput.mdx
apps/docs/content/components/Textarea.mdx
apps/next-docs/content/forms/Select/index.mdx
apps/next-docs/content/forms/TextArea/index.mdx
apps/next-docs/content/forms/TextInput/index.mdx

Adds an accessible label — either via `aria-label` or `FormControl` — to all Select, TextArea, and TextInput examples in the existing and next docs
Check that the labels make sense, and that I've not missed any
- Closes https://github.com/github/accessibility-audits/issues/10699
- Closes https://github.com/github/accessibility-audits/issues/10700
- Closes https://github.com/github/accessibility-audits/issues/10704

Ensure all Select, TextArea, and TextInput examples in docs have an accessible label

---

.changeset/hungry-tips-sing.md
packages/react/src/ActionMenu/ActionMenu.module.css

Fixes [an issue](https://github.slack.com/archives/C03FY9G00NS/p1747686318725149) in `ActionMenu` where anchor links in `split-button` mode were only clickable on the text. Now, the clickable area covers the full width and height of the item.
[Storybook](https://primer-b241c5b744-26139705.drafts.github.io/brand/storybook/?path=/story/components-actionmenu-features--split-button-mode)
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix `ActionMenu` split-button anchor size

---

.changeset/ten-carrots-appear.md
apps/docs/content/components/CTAForm/react.mdx
apps/docs/content/components/Checkbox/react.mdx
apps/docs/content/components/FormControl.mdx
apps/docs/content/components/RadioGroup/react.mdx
apps/next-docs/content/components/CTAForm/react.mdx
apps/next-docs/content/forms/Checkbox/react.mdx
apps/next-docs/content/forms/FormControl/index.mdx
apps/next-docs/content/forms/RadioGroup/react.mdx
packages/react/src/forms/Checkbox/Checkbox.stories.tsx
packages/react/src/forms/Checkbox/Checkbox.tsx
packages/react/src/forms/FormControl/FormControl.stories.tsx
packages/react/src/forms/Radio/Radio.tsx

Removed built-in `<label>` elements from `Checkbox` and `Radio` components. As these labels were only used to render the visual checkbox or radio button I was able to replace them with a `<span>` which forwards click events through to the underlying `<input>` in the same way a `<label>` would.
- Remove associated label from `Checkbox` and `Radio` components
- Labels should be provided via the `FormControl` component
- Moved `Checkbox` and `Radio` components to their logical place in the DOM in our docs examples
- Fixed a typo in our `RadioGroup` docs which mistakenly uses `CheckboxGroup` instead.
- Removed unused `ref` type from `Checkbox` and `Radio` components. We no longer need to declare it explicitly since #998.
- Check the docs to make sure I've not missed any `Checkbox` and `Radio` …

Remove label from Checkbox and Radio components

---

.changeset/tiny-bears-lick.md
packages/react/src/SubNav/SubNav.module.css

Increased the touch target size of `SubNav.SubMenu` toggle button to 24px × 24px.
The button was previously only 16px × 16px, and rather than add 4px to the left and right I've instead added 8px to the right (along with -8px of margin-right) so as to not cause any visual changes. You can see the touch target size change in the screenshots below.
- Check that you're happy with the focus styles, and that the touch target is indeed 24px × 24px.
- Closes https://github.com/github/primer/issues/4676
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Increase the touch target size of SubNav.SubMenu toggle button

---

.changeset/tame-shirts-stare.md
packages/react/src/ActionMenu/ActionMenu.test.tsx
packages/react/src/ActionMenu/ActionMenu.tsx

- Refactored the `ActionMenu.Item` component to remove branching logic ([previously discussed here](https://github.com/primer/brand/pull/972#discussion_r2042185895))
- Fixed a bug where `onClick` and `onKeyDown` weren't being called when provided.
- Fixed a bug where menu items could be cycled through using the <kbd>Tab</kbd> key, which resulted in unpredictable behaviour (see videos below). The intended way to navigate through the list is by using the arrow keys.
- Check that both the regular, and the link, versions of the `ActionMenuItem` still handle props in the same way.
- Closes #1019
<table>
<tr>
</tr>
<tr>
https://github.com/user-attachments/assets/dc8cd090-a6ad-4494-8bbc-7480fba221a8
</td> …

Refactor split ActionMenu and ensure onClick and onKeyDown get called when provided

---

.changeset/hot-ways-shout.md
packages/react/src/AnchorNav/AnchorNav.tsx

Removed `aria-describedby` from `AnchorNav.Link` component.
- If possible, test with a screen reader to ensure the heading content isn't announced after the navigation link.
- Otherwise, just verify via the rendered markup.
- Closes https://github.com/primer/brand/issues/1022
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Removed aria-describedby from `AnchorNav.Link` component

---

.changeset/polite-otters-compare.md
packages/react/src/SubNav/SubNav.tsx

Ensure subnav separator is always visible on large viewports

Ensure subnav separator is always visible on large viewports

---

.changeset/mean-pants-hear.md
.changeset/witty-dolls-sleep.md
packages/design-tokens/src/tokens/functional/components/logosuite/colors.json
packages/react/src/LogoSuite/LogoSuite.module.css

Resolves https://github.com/github/primer/issues/5240
Increases contrast of the play/pause button against animated logos in marquee mode. Logobar controls now have dedicated tokens, decoupling them from the Button styles they previously used. 
Note: Color choices now are parity (or closest match) with custom styles applied in Dotcom. E.g. from the custom video controls:
🔗 [Preview link](https://primer-bc8f0e7287-26139705.drafts.github.io/brand/storybook/?path=/story/components-logosuite-examples--following-hero&globals=colorMode:dark)
- Adds custom tokens for logobar controls, replacing the previous buttons ones
- Mostly affects dark mode, light mode relatively unchanged but still uses a dedicated a token if further user customization is needed
- Check we're happy with the color choice, …

Increased contrast of LogoSuite.Logobar play/pause button background

---

apps/docs/content/components/ActionMenu.mdx
apps/next-docs/content/components/ActionMenu/index.mdx

Closes https://github.com/primer/brand/issues/1021
Split-button mode in the ActionMenu component only works with links at this time. This adds some notice about this constraint to our public docs.
Gatsby docs
Next docs

Add note to action menu docs about split button mode links

---

apps/docs/content/components/ButtonGroup/react.mdx
apps/next-docs/content/components/ButtonGroup/react.mdx

Adds missing href to `ButtonGroup` examples in current and next docs.
- Closes https://github.com/github/primer/issues/3754

Add missing href to ButtonGroup link examples

---

packages/design-tokens/src/tokens/functional/colors/global.json
packages/e2e/scripts/playwright/axe-clean.spec.ts

Inspired by the recent improvements to our VRT tests, this PR parallelises our axe-playwright tests, used in our UI test / Accessibility action.
| Previous time taken | Time taken now | Improvement |
| --- | --- | --- | 
| 22 mins | 7 mins | **15 mins faster** 🎉 ⚡ |
See the Playwright docs on the change here: https://playwright.dev/docs/api/class-test#test-describe-configure
You can see from the checks associated with this PR that the action is completing successfully.
In an earlier commit (f80de414a31178cc0fcb6ded7fff9ef6f320e475) I intentionally triggered axe violations to test that they would still be reported. As you can see from [this run](https://github.com/primer/brand/actions/runs/15461299873/job/43523045254?pr=1040) they were reported successfully.
All of the axe tests run …

Parallelise playwright tests in axe-playwright action

---

.github/release_template.md

Adding two new items to the release testing checklist. These are kitchen sink pages, and will require the correct Staff flag to access. 
cc. @joshfarrant @danielguillan as PB release conductors

Update release testing checklist

---

.changeset/heavy-turtles-accept.md
packages/react/src/VideoPlayer/VideoPlayer.module.css
packages/react/src/VideoPlayer/VideoPlayer.test.tsx
packages/react/src/VideoPlayer/components/VideoTooltip/VideoTooltip.tsx

`VideoPlayer` tooltips no longer dismiss immediately and instead allow a small window of time in which the cursor can be moved from the trigger to the tooltip, at which point the tooltip will remain visible until the cursor leaves the tooltip.
- Check that the hovering works as expected
- Closes https://github.com/github/primer/issues/3802

Allow VideoPlayer tooltips to be hovered

---

.changeset/flat-pigs-dream.md
packages/react/src/SubNav/SubNav.features.stories.tsx
packages/react/src/SubNav/SubNav.tsx

Traps the focus inside the SubNav component when expanded on narrow viewports.
- Check that focus is trapped inside the expanded menu on viewports
- Check that focus moves as expected in other scenarios
1. Open a SubNav in the docs or Storybook (on a narrow viewport)
1. Using the keyboard, expand the collapsed menu
1. Tab through the menu and note that keyboard focus should remain trapped within the menu.
- Closes https://github.com/github/primer/issues/3796
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Trap focus inside SubNav component when expanded on narrow viewports

---

apps/next-docs/content/components/CTABanner/react.mdx
apps/next-docs/content/components/ComparisonTable/index.mdx
apps/next-docs/content/components/FAQ/react.mdx
apps/next-docs/content/components/FAQ/react.tsx
apps/next-docs/content/components/Pagination/index.mdx
apps/next-docs/content/components/SubdomainNavBar/index.mdx
apps/next-docs/content/components/VideoPlayer/index.mdx
apps/next-docs/content/forms/FormControl/index.mdx
apps/next-docs/content/forms/Select/index.mdx
apps/next-docs/content/forms/TextArea/index.mdx
apps/next-docs/content/forms/TextInput/index.mdx
apps/next-docs/content/introduction/theming.mdx
apps/next-docs/content/layout/Stack/react.mdx
apps/next-docs/content/typography/Text/react.mdx
apps/next-docs/package.json
package-lock.json

Various fixes to broken documentation pages on Next site.
- updates javascript code fence blocks
- adds some better formatting to prop tables (more to come later)
- Use `<div>` to prevent default horizontal flex ordering in previews, where they should be stacked vertically
Example of the many fixes to code blocks
<table>
<tr>
<th> Before (static)</th> <th> After (editable)</th>
</tr>
<tr>
</td>
</td>
</tr>
</table>

QA fixes for next docs: previews and prop values

---

apps/next-docs/app/layout.tsx

Resolves https://github.com/github/primer/issues/5379
Fixes bug where lack of trailing slash on top nav bar links is causing the URL rewrite to fail on the primer.style host. This fixes that by manually adding trailing slash.
1. Go to preview URL, and click on any of the top bar external links like Product UI
1. Observe that the correct destination is loaded, instead of the primer.style homepage

Add forward slash to next doc external links for primer.style

---

packages/react/src/FAQ/FAQ.tsx
packages/react/src/FAQ/FAQGroup.test.tsx
packages/react/src/FAQ/FAQGroup.tsx

In some circumstances (for example on `/features/copilot`) the FAQGroup could throw an error and not render.
This PR adds a bit of defensive code to ensure that the FAQGroup can handle null children gracefully.
-
-
1.
1.
1.
-
-

Fix bug where FAQGroup could throw an error if the grandchild was null

---

.changeset/witty-roses-attack.md
packages/react/src/EyebrowBanner/EyebrowBanner.test.tsx
packages/react/src/EyebrowBanner/EyebrowBanner.tsx

Adds non-breaking spaces between adjacent spans in `EyebrowBanner` component. 
Previously, NVDA would announce the `EyebrowBanner` in the following ways:
```
link    GitHub Universe: Dive in to AI, security, and DevExGet your tickets now to join us on Nov. 8-9.
link    NEWGitHub Copilot now available for Business
link    NEWGitHub Copilot now available for BusinessHarnessed for productivity. Designed for collaboration.
link    UPDATENow supports multiple languages
```
Now, it's announced with a pause between strings like _DevEx_ and _Get_, _Business_ and _Harnessed_, and _UPDATE_ and _Now_.
```
link     GitHub Universe: Dive in to AI, security, and DevEx Get your tickets now to join us on Nov. 8-9.
link     NEW GitHub Copilot now available for Business 
link     NEW GitHub Copilot now …
```

Add non-breaking spaces between adjacent spans in EyebrowBanner

---

.changeset/mighty-cameras-brake.md
packages/react/src/SubdomainNavBar/SubdomainNavBar.stories.tsx
packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx

Fixes props which were leaking into the DOM, both in Storybook and in the `SubdomainNavBar` component itself.
- Explicitly destructured props in `SubdomainNavBar.stories.tsx` to prevent props leaking into the DOM of rendered story.
- Removed unused `showOnlyOnNarrow` prop from `SubdomainNavBar.tsx` to prevent it leaking into the DOM and to fix a related warning in the unit tests.
- I can't see the `showOnlyOnNarrow` prop being used anywhere, and I'm not sure it was ever implemented since being added in #451. Another set of eyes on this would be appreciated though.
- Check that the SubdomainNavBar still works in the expected way.
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix leaking props in SubdomainNavBar to remove warning from unit tests

---

apps/next-docs/content/index.tsx

Fixes incorrect content on docs homepage. The last card currently references Product UI when it should be Brand UI. 
This card is just filler, so I've replaced it with Storybook like we previously had on the old docs. This now makes it easier to get to Storybook.
Also added in the version number of our latest release, and link to the release page like we used to have before.
- Verify homepage changes work as expected.
1. Go the homepage and check the links go to the correct places: Storybook and Releases pages
-
-
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Fix incorrect content on docs homepage

---

.changeset/great-kangaroos-switch.md
package-lock.json
packages/react/package.json

I tried to upgrade `@primer/behaviors` in `github/github-ui` but ran into a version conflict:
```
npm error ❌ Found mismatched sub-dependency versions for @primer/behaviors:
npm error     - 1.8.2 in node_modules/@primer/behaviors
npm error     - 1.8.0 in node_modules/@primer/react-brand/node_modules/@primer/behaviors
```
To fix this, this PR upgrades `@primer/behaviors` from `@primer/react-brand` and unlocks it so we don't run into this in the future for patch versions.

Upgrade `@primer/behaviors` and unlock it to patch versions

---

CODEOWNERS

I want to propose adding @primer/brand-reviewers as codeowners for the repository, so that we can turn on protections for pull requests to only be reviewed by memebers of that team.

Add brand-reviewers CODEOWNERS file for review assignments

---

packages/react/src/forms/Checkbox/Checkbox.test.tsx

Backfills tests for Checkbox component to bring coverage up to 100%.
- Towards https://github.com/github/primer/issues/5412

Add tests for Checkbox component

---

apps/next-docs/.eslintrc.cjs
apps/next-docs/next-env.d.ts
apps/next-docs/package.json
package-lock.json
package.json

Upgrades Next.js to address security vulnerabilities in currently used version.
Related to #1145 
Closes https://github.com/primer/brand/security/dependabot/335
Hoists the Next.js upgrade from there, as that PR is blocked.
- Bumps Next.js to latest version
- That is all
<table>
<tr>
</tr>
<tr>
</td>
</td>
</tr>
</table>

Upgrade Next.js dep

---

packages/react/jest.config.js

Excludes the following directories from the coverage report
- `packages/react/src/recipes`
- `packages/react/src/fixtures`
- `packages/react/src/test-utils`
This gives us a more accurate figure for our overall test coverage of 85.34%, compared to 77.22% that was reported before

Exclude recipes, fixtures, and test-utils from coverage

---

.changeset/quiet-impalas-pay.md
packages/react/src/Icon/Icon.module.css

Icon component SVGs are currently affected by font styles and metrics, which can cause them to appear off-center in certain situations. This PR addresses this issue. Resolves https://github.com/orgs/github/projects/4709/views/1?pane=issue&itemId=127920860&issue=primer%7Cbrand%7C1154.
- Makes `svg` elements inside `Icon` display `block` instead of `inline-block`
- There are no visual changes because the current version of Mona Sans used in Primer Brand does not affect the icons, unlike the dotcom version.
-  Ensure there are no regressions in `Icon` and other components that use `Icon`.
-  Test the canary release in `github/github-ui` to verify that the vertical alignment issue reported in  https://github.com/orgs/github/projects/4709/views/1?pane=issue&itemId=127920860&issue=primer%7Cbrand …

Ensure Icon SVGs are properly vertically aligned

---

.changeset/olive-planets-live.md
packages/react/src/IDE/IDE.tsx
packages/react/src/hooks/useTabs.test.tsx
packages/react/src/hooks/useTabs.ts

Improves types in `useTabs` hook, improves `useTabs` tests, and fixes an accessibility issue in the IDE component which these type improvements automatically highlighted.
- Fixes incorrect `onClick`, `onKeyDown`, and `onFocus` types
- Enforces that either a `label` or `labelledBy` is passed to `getTabListProps()`
- Updates the `focusTab` function to only focus the element and nothing else. `onFocus` will handle the state updates. Previously two duplicate state updates were being triggered.
- Generally makes typings in the hook more accurate
- Removes `@ts-expect-error` from `useTabs.test.tsx`, now that the types are fixed
- Adds a missing `label` to the tablist in the IDE component which was highlighted by these type improvements (thanks, TypeScript! 🎉)
- Check out the test tweaks
- Make …

Improves types in useTabs hook
